[project]
name = "can-log-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cantools>=39.4.11",
    "matplotlib>=3.9.2",
    "pyqt5-qt5==5.15.2 ; platform_system == 'Windows'",
    "ruff>=0.7.3",
]
