name: CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover test

    - name: Check code quality with flake8
      run: |
        pip install flake8
        flake8 src test

    - name: Static code analysis with pylint
      run: |
        pip install pylint
        pylint src test

    - name: Run security checks
      run: |
        pip install bandit
        bandit -r src test
